spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://192.168.159.138:8084
  zipkin:
    base-url: http://192.168.159.138:9411

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.159.138
  client:
    #表示是否将自己注册到Eureka，因为要构建集群环境，需要将自己注册到集群，所以应该开启
    registerWithEureka: true
    #百世是否从Eureka获取注册信息，如果是单一节点，不需要同步其他Eureka节点，则可以设置成false，但此处为集群的话，应该设置为true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.159.138:8761/eureka/,http://192.168.159.138:8861/eureka/,http://192.168.159.138:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info